baseURL: "https://ndieckow.github.io/"
languageCode: "en-us"
title: Niklas Dieckow
theme: stack
copyright: Niklas Dieckow

params:
  homeInfoParams:
    Title: Niklas' Blog
    Content: On this blog, I'll share what I'm currently working on and thinking about.

  socialIcons: # optional
    - name: GitHub
      url: "https://github.com/ndieckow"
  
  showReadingTime: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
  sidebar:
    compact: false
    emoji: "ðŸš€"
    subtitle: "PhD student at the Research Group for Human-Centric AI, TUHH"
    avatar:
      enabled: false

  article:
    math: true
    readingTime: true

  widgets:
    homepage:
      - type: "search"
        params: {}
      - type: "archives"
        params: {}   
      - type: "categories"
        params: {}
      - type: "tag-cloud"
        params: {}
    page:
      - type: "search"
        params: {}
      - type: "toc"
        params: {}

outputs:
  home:
    - HTML
    - RSS
    - JSON